### ISSUE TITLE
Is there retry logic for bad connections?

### ISSUE THREAD

**Issue by pulkitsinghal** [tyabonil/request-promise#33]
Just wondering if the library itself has a utility flag/method or someone has a gist for retrying requests automatically?

For example, usecases like:
1) 429 based rate limiting might require pause and retry
2) connection timeout might require a retry

**Comment by analog-nico** [comment]
Hi @pulkitsinghal this library exists solely for adding Promise support. However, there is [limit-request-promise](https://github.com/you21979/node-limit-request-promise) built on top of request-promise that might be what you are looking for.

**Comment by analog-nico** [comment]
Hi @pulkitsinghal did my answer help you? Anything else I could help you with?
If you are good I would close this issue.

**Comment by pulkitsinghal** [comment]
Please close it.

**Comment by analog-nico** [comment]
Feel free to ping me anytime. :)
