### ISSUE TITLE
Use require-new to load request

### ISSUE THREAD

**Issue by gajus** [tyabonil/request-promise#35]
https://github.com/tyabonil/request-promise/blob/master/lib/rp.js#L10-L28 this can be replaced with https://www.npmjs.com/package/require-new (I am the author of `require-new` library).

**Comment by analog-nico** [comment]
Good point. I already thought it would make a good module. Actually your module (and other similar ones as well) lacks considering dependent modules. If I require-new a file I want to make sure that all files that this file requires are also required-new. That is why I clear the whole cache in my code.

How about joining forces to extend your lib? What do you think?

**Comment by gajus** [comment]
A simple workaround would be to temporary backup the entire `require.cache` and then restore it after the operation.

> How about joining forces to extend your lib? What do you think?

Drop me an email to gk@anuary.com
