### ISSUE TITLE
Weird issue when using Promise.settle w/ array of request-promises using `.finally()`

### ISSUE THREAD

**Issue by chiefy** [tyabonil/request-promise#37]
I have an array of request-promises that I am sending to `Promise.settle`, in each of these promises I am using the `.finally()` method and doing a `return Promise.resolve(some_val);` yet when I inspect my resolved value in the settle resolution, the Bluebird `value()` method returns `undefined`. 

This seems to resolve itself if I move returning a new Promise inside my catch or then on the original request-promise. 

doesn't work:
```
...
var req = rq('http://failing_domain_doesnt_resolve.com')
    .then(function(){})
    .catch(function(err){ // this gets called ok })
    .finally(function() {
         return Promise.resolve('I am ok!');
    });

Promise.settle([req])
    .then(function(results) {
        console.info(results[0].value()); // undefined
     });
```
Thanks for your work on this!

**Comment by analog-nico** [comment]
Hi @chiefy this is more about the use of Bluebird promises. In its [API docs](https://github.com/petkaantonov/bluebird/blob/master/API.md#finallyfunction-handler---promise) it says:
> There are special semantics for `.finally()` in that the final value cannot be modified from the handler.

This means whatever you return inside `.finally()` doesn't have an effect. However, in your case you can just use `.then()`:
``` js
var req = rq('http://failing_domain_doesnt_resolve.com')
    .then(function(){})
    .catch(function(err){ // this gets called ok })
    .then(function() {
         return Promise.resolve('I am ok!');
    });
```

**Comment by chiefy** [comment]
@analog-nico thanks man - I did read the docs (really) must've just slipped by me.

**Comment by analog-nico** [comment]
Don't mind. ;) Have a nice day!
