### ISSUE TITLE
post param

### ISSUE THREAD

**Issue by FredericHeem** [tyabonil/request-promise#39]
Dear,
Is it possible to add a post parameter ? I couldn't find a way to add them and couldn't find neither a test nor an example.

**Comment by analog-nico** [comment]
Hi @FredericHeem Request-Promise has the exact same API as [Request](https://github.com/request/request). Only that you can now use promises instead of callbacks. In particular it means you can use alls [options](https://github.com/request/request#requestoptions-callback) Request provides as well:

``` js
rp({
    uri : 'http://posttestserver.com/post.php',
    method : 'POST',
    qs: {
      name: 'some name',
      email: 'john@example.com'
    }
  })
  .then(function (body) {
    // ...
  });
```

Or even the shorthand Request provides:

``` js
rp.post({
    uri : 'http://posttestserver.com/post.php',
    qs: {
      name: 'some name',
      email: 'john@example.com'
    }
  })
  .then(function (body) {
    // ...
  });
```

Is that what you were looking for or did I miss your point?

**Comment by FredericHeem** [comment]
I meant post parameter in the body, not as a query string, FYI, this is the function that is supposed to be ported to request-promises:
```
Client.prototype._ops = function(ops, action, resCodes, param) {
    var me = this;
    var deferred = Q.defer();
    var data = updateRequestWithKey(this, {});
    if(param){
        data.json = param;
    }
    data.method = ops;
  
    request(this.url + action, data, function(err, res, body) {
       
        if (err) {
            return deferred.reject(err)
        }
        if (resCodes.indexOf(res.statusCode) == -1){
            return deferred.reject(bodyToError(body))
        } else {
            deferred.resolve(body);
        }
    })
    return deferred.promise;
}
```

**Comment by analog-nico** [comment]
Oh, interesting. I didn't know of the possibility to pass the data as the second parameter. Is this somewhere documented? I looked through Request's whole README and didn't find it.

Could you give me an actual data object I can use for writing a test?

**Comment by analog-nico** [comment]
I just made the following test which is successful:

``` js
it('for passing the data as second parameter', function (done) {

    rp('http://localhost:4000/200', { method: 'POST' })
        .then(function (body) {
            expect(body).to.eql('POST /200');
            done();
        })
        .catch(done);

});
```

Does this reproduce your scenario?

**Comment by FredericHeem** [comment]
Do yo mind to try this ?
```
it('for passing the data as second parameter with data', function (done) {

    rp('http://localhost:4000/200', { method: 'POST', data: { json : {foo:"bar"}} })
        .then(function (body) {
            expect(body).to.eql('POST /200');
            done();
        })
        .catch(done);

});
```

**Comment by analog-nico** [comment]
This one is successful:

``` js
it('for passing the data as the second parameter', function (done) {

    rp('http://localhost:4000/200', { method: 'POST', json: { foo: 'bar' } })
        .then(function (body) {
            expect(body).to.eql('POST /200 - {"foo":"bar"}');
            done();
        })
        .catch(done);

});
```

I had to change `data: { json : {foo:"bar"}}` to just `json: { foo: 'bar' }`. Anyway, I tested the same with plain Request and there it behaved exactly the same.

BTW, in theory any use case that works with plain Request should work with Request-Promise as well because Request-Promise is not a wrapper. It exposes the actual Request object. Anyway, that is just theory and now I wonder why your code is not working. Any ideas?

**Comment by analog-nico** [comment]
Hi @FredericHeem did you find the cause or can I help you somehow finding it?

**Comment by FredericHeem** [comment]
For the time being, I sticked with Promise.promisify(request). 
Thanks for your support

**Comment by fritx** [comment]
Btw, what's the difference between `bluebird.promisify` and `request-promise`?

**Comment by analog-nico** [comment]
Hi @fritx Request-Promise is of course better tailored towards how Request is used. In particular, the [`simple` option](https://github.com/request/request-promise#thenonfulfilled-onrejected) better devides which responses go to `.then(...)` and which responses go to `.catch(...)`. Overall the requests can be written in a cleaner way.

**Comment by fritx** [comment]
Thanks for explanation!
